<?php 
/** super store map region and language list **/
function super_store_region_list() {
	$regions = array (
	    array('value' => 'World', 'name' => 'World Wide (Default)'),
	    array('value' => 'US', 'name' => 'United States'),
		array('value' => 'AF', 'name' => 'Afghanistan'),
		array('value' => 'AL', 'name' => 'Albania'),
		array('value' => 'DZ', 'name' => 'Algeria'),
		array('value' => 'AS', 'name' => 'American Samoa'),
		array('value' => 'AD', 'name' => 'Andorra'),
		array('value' => 'AO', 'name' => 'Angola'),
		array('value' => 'AI', 'name' => 'Anguilla'),
		array('value' => 'AQ', 'name' => 'Antarctica'),
		array('value' => 'AG', 'name' => 'Antigua & Barbuda'),
		array('value' => 'AR', 'name' => 'Argentina'),
		array('value' => 'AM', 'name' => 'Armenia'),
		array('value' => 'AW', 'name' => 'Aruba'),
		array('value' => 'AC', 'name' => 'Ascension Island'),
		array('value' => 'AU', 'name' => 'Australia'),
		array('value' => 'AT', 'name' => 'Austria'),
		array('value' => 'AZ', 'name' => 'Azerbaijan'),
		array('value' => 'BS', 'name' => 'Bahamas'),
		array('value' => 'BH', 'name' => 'Bahrain'),
		array('value' => 'BD', 'name' => 'Bangladesh'),
		array('value' => 'BB', 'name' => 'Barbados'),
		array('value' => 'BY', 'name' => 'Belarus'),
		array('value' => 'BE', 'name' => 'Belgium'),
		array('value' => 'BZ', 'name' => 'Belize'),
		array('value' => 'BJ', 'name' => 'Benin'),
		array('value' => 'BM', 'name' => 'Bermuda'),
		array('value' => 'BT', 'name' => 'Bhutan'),
		array('value' => 'BO', 'name' => 'Bolivia'),
		array('value' => 'BA', 'name' => 'Bosnia & Herzegovina'),
		array('value' => 'BW', 'name' => 'Botswana'),
		array('value' => 'BV', 'name' => 'Bouvet Island'),
		array('value' => 'BR', 'name' => 'Brazil'),
		array('value' => 'IO', 'name' => 'British Indian Ocean Territory'),
		array('value' => 'VG', 'name' => 'British Virgin Islands'),
		array('value' => 'BN', 'name' => 'Brunei'),
		array('value' => 'BG', 'name' => 'Bulgaria'),
		array('value' => 'BF', 'name' => 'Burkina Faso'),
		array('value' => 'BI', 'name' => 'Burundi'),
		array('value' => 'KH', 'name' => 'Cambodia'),
		array('value' => 'CM', 'name' => 'Cameroon'),
		array('value' => 'CA', 'name' => 'Canada'),
		array('value' => 'IC', 'name' => 'Canary Islands'),
		array('value' => 'CV', 'name' => 'Cape Verde'),
		array('value' => 'BQ', 'name' => 'Caribbean Netherlands'),
		array('value' => 'KY', 'name' => 'Cayman Islands'),
		array('value' => 'CF', 'name' => 'Central African Republic'),
		array('value' => 'EA', 'name' => 'Ceuta & Melilla'),
		array('value' => 'TD', 'name' => 'Chad'),
		array('value' => 'CL', 'name' => 'Chile'),
		array('value' => 'CN', 'name' => 'China'),
		array('value' => 'CX', 'name' => 'Christmas Island'),
		array('value' => 'CP', 'name' => 'Clipperton Island'),
		array('value' => 'CC', 'name' => 'Cocos (Keeling) Islands'),
		array('value' => 'CO', 'name' => 'Colombia'),
		array('value' => 'KM', 'name' => 'Comoros'),
		array('value' => 'CD', 'name' => 'Congo (DRC)'),
		array('value' => 'CG', 'name' => 'Congo (Republic)'),
		array('value' => 'CK', 'name' => 'Cook Islands'),
		array('value' => 'CR', 'name' => 'Costa Rica'),
		array('value' => 'HR', 'name' => 'Croatia'),
		array('value' => 'CU', 'name' => 'Cuba'),
		array('value' => 'CW', 'name' => 'Curaçao'),
		array('value' => 'CY', 'name' => 'Cyprus'),
		array('value' => 'CZ', 'name' => 'Czech Republic'),
		array('value' => 'CI', 'name' => 'Côte d’Ivoire'),
		array('value' => 'DK', 'name' => 'Denmark'),
		array('value' => 'DG', 'name' => 'Diego Garcia'),
		array('value' => 'DJ', 'name' => 'Djibouti'),
		array('value' => 'DM', 'name' => 'Dominica'),
		array('value' => 'DO', 'name' => 'Dominican Republic'),
		array('value' => 'EC', 'name' => 'Ecuador'),
		array('value' => 'EG', 'name' => 'Egypt'),
		array('value' => 'SV', 'name' => 'El Salvador'),
		array('value' => 'GQ', 'name' => 'Equatorial Guinea'),
		array('value' => 'ER', 'name' => 'Eritrea'),
		array('value' => 'EE', 'name' => 'Estonia'),
		array('value' => 'ET', 'name' => 'Ethiopia'),
		array('value' => 'FK', 'name' => 'Falkland Islands (Islas Malvinas)'),
		array('value' => 'FO', 'name' => 'Faroe Islands'),
		array('value' => 'FJ', 'name' => 'Fiji'),
		array('value' => 'FI', 'name' => 'Finland'),
		array('value' => 'FR', 'name' => 'France'),
		array('value' => 'GF', 'name' => 'French Guiana'),
		array('value' => 'PF', 'name' => 'French Polynesia'),
		array('value' => 'TF', 'name' => 'French Southern Territories'),
		array('value' => 'GA', 'name' => 'Gabon'),
		array('value' => 'GM', 'name' => 'Gambia'),
		array('value' => 'GE', 'name' => 'Georgia'),
		array('value' => 'DE', 'name' => 'Germany'),
		array('value' => 'GH', 'name' => 'Ghana'),
		array('value' => 'GI', 'name' => 'Gibraltar'),
		array('value' => 'GR', 'name' => 'Greece'),
		array('value' => 'GL', 'name' => 'Greenland'),
		array('value' => 'GD', 'name' => 'Grenada'),
		array('value' => 'GP', 'name' => 'Guadeloupe'),
		array('value' => 'GU', 'name' => 'Guam'),
		array('value' => 'GT', 'name' => 'Guatemala'),
		array('value' => 'GG', 'name' => 'Guernsey'),
		array('value' => 'GN', 'name' => 'Guinea'),
		array('value' => 'GW', 'name' => 'Guinea-Bissau'),
		array('value' => 'GY', 'name' => 'Guyana'),
		array('value' => 'HT', 'name' => 'Haiti'),
		array('value' => 'HM', 'name' => 'Heard & McDonald Islands'),
		array('value' => 'HN', 'name' => 'Honduras'),
		array('value' => 'HK', 'name' => 'Hong Kong'),
		array('value' => 'HU', 'name' => 'Hungary'),
		array('value' => 'IS', 'name' => 'Iceland'),
		array('value' => 'IN', 'name' => 'India'),
		array('value' => 'ID', 'name' => 'Indonesia'),
		array('value' => 'IR', 'name' => 'Iran'),
		array('value' => 'IQ', 'name' => 'Iraq'),
		array('value' => 'IE', 'name' => 'Ireland'),
		array('value' => 'IM', 'name' => 'Isle of Man'),
		array('value' => 'IL', 'name' => 'Israel'),
		array('value' => 'IT', 'name' => 'Italy'),
		array('value' => 'JM', 'name' => 'Jamaica'),
		array('value' => 'JP', 'name' => 'Japan'),
		array('value' => 'JE', 'name' => 'Jersey'),
		array('value' => 'JO', 'name' => 'Jordan'),
		array('value' => 'KZ', 'name' => 'Kazakhstan'),
		array('value' => 'KE', 'name' => 'Kenya'),
		array('value' => 'KI', 'name' => 'Kiribati'),
		array('value' => 'XK', 'name' => 'Kosovo'),
		array('value' => 'KW', 'name' => 'Kuwait'),
		array('value' => 'KG', 'name' => 'Kyrgyzstan'),
		array('value' => 'LA', 'name' => 'Laos'),
		array('value' => 'LV', 'name' => 'Latvia'),
		array('value' => 'LB', 'name' => 'Lebanon'),
		array('value' => 'LS', 'name' => 'Lesotho'),
		array('value' => 'LR', 'name' => 'Liberia'),
		array('value' => 'LY', 'name' => 'Libya'),
		array('value' => 'LI', 'name' => 'Liechtenstein'),
		array('value' => 'LT', 'name' => 'Lithuania'),
		array('value' => 'LU', 'name' => 'Luxembourg'),
		array('value' => 'MO', 'name' => 'Macau'),
		array('value' => 'MK', 'name' => 'Macedonia (FYROM)'),
		array('value' => 'MG', 'name' => 'Madagascar'),
		array('value' => 'MW', 'name' => 'Malawi'),
		array('value' => 'MY', 'name' => 'Malaysia'),
		array('value' => 'MV', 'name' => 'Maldives'),
		array('value' => 'ML', 'name' => 'Mali'),
		array('value' => 'MT', 'name' => 'Malta'),
		array('value' => 'MH', 'name' => 'Marshall Islands'),
		array('value' => 'MQ', 'name' => 'Martinique'),
		array('value' => 'MR', 'name' => 'Mauritania'),
		array('value' => 'MU', 'name' => 'Mauritius'),
		array('value' => 'YT', 'name' => 'Mayotte'),
		array('value' => 'MX', 'name' => 'Mexico'),
		array('value' => 'FM', 'name' => 'Micronesia'),
		array('value' => 'MD', 'name' => 'Moldova'),
		array('value' => 'MC', 'name' => 'Monaco'),
		array('value' => 'MN', 'name' => 'Mongolia'),
		array('value' => 'ME', 'name' => 'Montenegro'),
		array('value' => 'MS', 'name' => 'Montserrat'),
		array('value' => 'MA', 'name' => 'Morocco'),
		array('value' => 'MZ', 'name' => 'Mozambique'),
		array('value' => 'MM', 'name' => 'Myanmar (Burma)'),
		array('value' => 'NA', 'name' => 'Namibia'),
		array('value' => 'NR', 'name' => 'Nauru'),
		array('value' => 'NP', 'name' => 'Nepal'),
		array('value' => 'NL', 'name' => 'Netherlands'),
		array('value' => 'NC', 'name' => 'New Caledonia'),
		array('value' => 'NZ', 'name' => 'New Zealand'),
		array('value' => 'NI', 'name' => 'Nicaragua'),
		array('value' => 'NE', 'name' => 'Niger'),
		array('value' => 'NG', 'name' => 'Nigeria'),
		array('value' => 'NU', 'name' => 'Niue'),
		array('value' => 'NF', 'name' => 'Norfolk Island'),
		array('value' => 'KP', 'name' => 'North Korea'),
		array('value' => 'MP', 'name' => 'Northern Mariana Islands'),
		array('value' => 'NO', 'name' => 'Norway'),
		array('value' => 'OM', 'name' => 'Oman'),
		array('value' => 'PK', 'name' => 'Pakistan'),
		array('value' => 'PW', 'name' => 'Palau'),
		array('value' => 'PS', 'name' => 'Palestine'),
		array('value' => 'PA', 'name' => 'Panama'),
		array('value' => 'PG', 'name' => 'Papua New Guinea'),
		array('value' => 'PY', 'name' => 'Paraguay'),
		array('value' => 'PE', 'name' => 'Peru'),
		array('value' => 'PH', 'name' => 'Philippines'),
		array('value' => 'PN', 'name' => 'Pitcairn Islands'),
		array('value' => 'PL', 'name' => 'Poland'),
		array('value' => 'PT', 'name' => 'Portugal'),
		array('value' => 'PR', 'name' => 'Puerto Rico'),
		array('value' => 'QA', 'name' => 'Qatar'),
		array('value' => 'RO', 'name' => 'Romania'),
		array('value' => 'RU', 'name' => 'Russia'),
		array('value' => 'RW', 'name' => 'Rwanda'),
		array('value' => 'RE', 'name' => 'Réunion'),
		array('value' => 'WS', 'name' => 'Samoa'),
		array('value' => 'SM', 'name' => 'San Marino'),
		array('value' => 'SA', 'name' => 'Saudi Arabia'),
		array('value' => 'SN', 'name' => 'Senegal'),
		array('value' => 'RS', 'name' => 'Serbia'),
		array('value' => 'SC', 'name' => 'Seychelles'),
		array('value' => 'SL', 'name' => 'Sierra Leone'),
		array('value' => 'SG', 'name' => 'Singapore'),
		array('value' => 'SX', 'name' => 'Sint Maarten'),
		array('value' => 'SK', 'name' => 'Slovakia'),
		array('value' => 'SI', 'name' => 'Slovenia'),
		array('value' => 'SB', 'name' => 'Solomon Islands'),
		array('value' => 'SO', 'name' => 'Somalia'),
		array('value' => 'ZA', 'name' => 'South Africa'),
		array('value' => 'GS', 'name' => 'South Georgia & South Sandwich Islands'),
		array('value' => 'KR', 'name' => 'South Korea'),
		array('value' => 'SS', 'name' => 'South Sudan'),
		array('value' => 'ES', 'name' => 'Spain'),
		array('value' => 'LK', 'name' => 'Sri Lanka'),
		array('value' => 'BL', 'name' => 'St. Barthélemy'),
		array('value' => 'SH', 'name' => 'St. Helena'),
		array('value' => 'KN', 'name' => 'St. Kitts & Nevis'),
		array('value' => 'LC', 'name' => 'St. Lucia'),
		array('value' => 'MF', 'name' => 'St. Martin'),
		array('value' => 'PM', 'name' => 'St. Pierre & Miquelon'),
		array('value' => 'VC', 'name' => 'St. Vincent & Grenadines'),
		array('value' => 'SD', 'name' => 'Sudan'),
		array('value' => 'SR', 'name' => 'Suriname'),
		array('value' => 'SJ', 'name' => 'Svalbard & Jan Mayen'),
		array('value' => 'SZ', 'name' => 'Swaziland'),
		array('value' => 'SE', 'name' => 'Sweden'),
		array('value' => 'CH', 'name' => 'Switzerland'),
		array('value' => 'SY', 'name' => 'Syria'),
		array('value' => 'ST', 'name' => 'São Tomé & Príncipe'),
		array('value' => 'TW', 'name' => 'Taiwan'),
		array('value' => 'TJ', 'name' => 'Tajikistan'),
		array('value' => 'TZ', 'name' => 'Tanzania'),
		array('value' => 'TH', 'name' => 'Thailand'),
		array('value' => 'TL', 'name' => 'Timor-Leste'),
		array('value' => 'TG', 'name' => 'Togo'),
		array('value' => 'TK', 'name' => 'Tokelau'),
		array('value' => 'TO', 'name' => 'Tonga'),
		array('value' => 'TT', 'name' => 'Trinidad & Tobago'),
		array('value' => 'TA', 'name' => 'Tristan da Cunha'),
		array('value' => 'TN', 'name' => 'Tunisia'),
		array('value' => 'TR', 'name' => 'Turkey'),
		array('value' => 'TM', 'name' => 'Turkmenistan'),
		array('value' => 'TC', 'name' => 'Turks & Caicos Islands'),
		array('value' => 'TV', 'name' => 'Tuvalu'),
		array('value' => 'UM', 'name' => 'U.S. Outlying Islands'),
		array('value' => 'VI', 'name' => 'U.S. Virgin Islands'),
		array('value' => 'UG', 'name' => 'Uganda'),
		array('value' => 'UA', 'name' => 'Ukraine'),
		array('value' => 'AE', 'name' => 'United Arab Emirates'),
		array('value' => 'GB', 'name' => 'United Kingdom'),		
		array('value' => 'UY', 'name' => 'Uruguay'),
		array('value' => 'UZ', 'name' => 'Uzbekistan'),
		array('value' => 'VU', 'name' => 'Vanuatu'),
		array('value' => 'VA', 'name' => 'Vatican City'),
		array('value' => 'VE', 'name' => 'Venezuela'),
		array('value' => 'VN', 'name' => 'Vietnam'),
		array('value' => 'WF', 'name' => 'Wallis & Futuna'),
		array('value' => 'EH', 'name' => 'Western Sahara'),
		array('value' => 'YE', 'name' => 'Yemen'),
		array('value' => 'ZM', 'name' => 'Zambia'),
		array('value' => 'ZW', 'name' => 'Zimbabwe'),
		array('value' => 'AX', 'name' => 'Åland Islands'),
	);
  return $regions;
}

function super_store_language_list(){
	$mapLanguage = array (
	    array('value' => 'en', 'name' => 'English (Default)'),
		array('value' => 'ar', 'name' => 'Arabic'),
		array('value' => 'kn', 'name' => 'Kannada'),
		array('value' => 'bg', 'name' => 'Bulgarian'),
		array('value' => 'ko', 'name' => 'Korean'),
		array('value' => 'bn', 'name' => 'Bengali'),
		array('value' => 'lt', 'name' => 'Lithuanian'),
		array('value' => 'ca', 'name' => 'Catalan'),
		array('value' => 'lv', 'name' => 'Latvian'),
		array('value' => 'cs', 'name' => 'Czech'),
		array('value' => 'ml', 'name' => 'Malayalam'),
		array('value' => 'da', 'name' => 'Danish'),
		array('value' => 'mr', 'name' => 'Marathi'),
		array('value' => 'de', 'name' => 'German'),
		array('value' => 'nl', 'name' => 'Dutch'),
		array('value' => 'el', 'name' => 'Greek'),
		array('value' => 'no', 'name' => 'Norwegian'),
		array('value' => 'pl', 'name' => 'Polish'),
		array('value' => 'en-AU', 'name' => 'English (Australian)'),
		array('value' => 'pt', 'name' => 'Portuguese'),
		array('value' => 'en-GB', 'name' => 'English (Great Britain)'),
		array('value' => 'pt-BR', 'name' => 'Portuguese (Brazil)'),
		array('value' => 'es', 'name' => 'Spanish'),
		array('value' => 'pt-PT', 'name' => 'Portuguese (Portugal)'),
		array('value' => 'eu', 'name' => 'Basque'),
		array('value' => 'ro', 'name' => 'Romanian'),
		array('value' => 'eu', 'name' => 'Basque'),
		array('value' => 'ru', 'name' => 'Russian'),
		array('value' => 'fa', 'name' => 'Farsi'),
		array('value' => 'sk', 'name' => 'Slovak'),
		array('value' => 'fi', 'name' => 'Finnish'),
		array('value' => 'sl', 'name' => 'Slovenian'),
		array('value' => 'fil', 'name' => 'Filipino'),
		array('value' => 'sr', 'name' => 'Serbian'),
		array('value' => 'fr', 'name' => 'French'),
		array('value' => 'sv', 'name' => 'Swedish'),
		array('value' => 'gl', 'name' => 'Galician'),
		array('value' => 'ta', 'name' => 'Tamil'),
		array('value' => 'gu', 'name' => 'Gujarati'),
		array('value' => 'te', 'name' => 'Telugu'),
		array('value' => 'hi', 'name' => 'Hindi'),
		array('value' => 'th', 'name' => 'Thai'),
		array('value' => 'hr', 'name' => 'Croatian'),
		array('value' => 'tl', 'name' => 'Tagalog'),
		array('value' => 'hu', 'name' => 'Hungarian'),
		array('value' => 'tr', 'name' => 'Turkish'),
		array('value' => 'id', 'name' => 'Indonesian'),
		array('value' => 'uk', 'name' => 'Ukrainian'),
		array('value' => 'it', 'name' => 'Italian'),
		array('value' => 'vi', 'name' => 'Vietnamese'),
		array('value' => 'iw', 'name' => 'Hebrew'),
		array('value' => 'zh-CN', 'name' => 'Chinese (Simplified)'),
		array('value' => 'ja', 'name' => 'Japanese'),
		array('value' => 'zh-TW', 'name' => 'Chinese (Traditional)'),
	);
	return $mapLanguage;
}
?>